import Modal from "@/components/Modal";
import Sidebar from "@/components/Sidebar";
import SinglePost from "@/components/SinglePost";
import Trending from "@/components/Trending";
import { AppContext } from "@/lib/contexts/AppContext";
import Head from "next/head";
import React, { useContext } from "react";

export default function PostPage() {
  const [appContext] = useContext(AppContext);

  return (
    <div>
      <Head>
        <title>Tweet Reply</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="relative max-w-[1400px] mx-auto">
        <Sidebar />
        <div className="flex gap-6">
          <SinglePost />
          <Trending />

          {appContext?.isModalOpen && <Modal />}
        </div>
      </main>
    </div>
  );
}
